name: 'segment_integration_tests'
version: '1.0'
config-version: 2

seed-paths: ["seeds"]

profile: 'integration_tests'

vars:
  dbt_segment:
    segment_page_views_table: "{{ ref('example_segment_pages') }}"

seeds:
  +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
