name: dbt_octafx

version: "0.1.0"

require-dbt-version: ">=0.17.2"

profile: "default"

target-path: "target"
clean-targets:
  - "dbt_packages"
  - "target"

vars:
  campaign_id: 66223aafe3b419a0a4b87ae4
  start: 2024-04-19
  end: 2024-04-24
  action_id: 48
  symbol_name: XAUUSD
  random_users: false

models:
  dbt_octafx:
    +materialized: view
