name: dbt_octafx

dbt-cloud:
  project-id: 362822

profile: "default"

target-path: "target"
clean-targets:
  - "target"

vars:
  campaign_id: 662cf1c9ebde3979bc61f3a8
  start: 2024-04-26
  end: 2024-05-03
  action_id: 5
  symbol_name: XAUUSD
  random_users: false

models:
  dbt_octafx:
    +materialized: view
