name: dbt_octafx

version: "0.1.0"

require-dbt-version: ">=0.17.2"

profile: "default"

target-path: "target"
clean-targets:
  - "target"

vars:
  campaign_id: 65733b51df03a1daadeb772d
  start: 2024-04-02
  end: 2024-04-09
  action_id: 437
  symbol_name: XAUUSD
  random_users: false
  dbt_dq_tool_schema: AUDIT

on-run-end:
  - "{{ dq_tools.store_test_results(results) }}"

models:
  dbt_octafx:
    +materialized: view
