sources:
    - name: wh_raw
      database: analytics-147612
      schema: wh_raw
      tables:
        - name: trading_real_raw
        - name: mobile_appsflyer
        - name: users
        - name: appsflyer_uninstall_events_report
        - name: trading_otr_deals_real
        - name: trading_otr_accounts_real
    - name: bloomreach
      database: analytics-147612
      schema: bloomreach_raw
      tables:
        - name: campaign
        - name: customers_properties
    - name: amplitude
      database: analytics-147612
      schema: amplitude
      tables:
        - name: events_octa_raw_app_feed_reading
        - name: events_octa_raw_web_feed_reading

