sources:
  - name: wh_raw
    database: analytics-147612
    schema: wh_raw
    tables:
      - name: trading_real_raw
        meta:
          metriql:
            deals_cnt:
              aggregation: count
        columns:
          - name: user_id
            meta:
              metriql.dimension:
                name: user_id
                type: integer
      - name: users
      - name: mobile_appsflyer
      - name: appsflyer_uninstall_events_report
      - name: users_cids_all
  - name: supplement
    database: analytics-147612
    schema: dev_gsokolov
    tables:
      - name: eth_recom
      - name: random_users
      - name: eligible_users
  - name: bloomreach
    database: analytics-147612
    schema: bloomreach_raw
    tables:
      - name: campaign
      - name: banner

models:
  - name: user_deals
    meta: 
      metriql:
        columns:
          - name: user_id
            meta:
              metriql.dimension:
                type: string
          - name: symbol_name
            meta:
              metriql.dimension:
                type: string
          - name: deals_cnt
            description: total number of deals
            meta:
              metriql.measure:
                aggregation: count
