version: 2


sources:
    - name: wh_raw
      database: analytics-147612
      schema: wh_raw
      tables:
        - name: trading_real_raw
        - name: mobile_appsflyer
        - name: users
        - name: appsflyer_uninstall_events_report
        - name: trading_otr_deals_real
        - name: trading_otr_accounts_real
    - name: bloomreach
      database: analytics-147612
      schema: bloomreach_raw
      tables:
        - name: campaign
        - name: customers_properties
    - name: amplitude
      database: analytics-147612
      schema: amplitude
      tables:
        - name: events_octa_raw_app_feed_reading
        - name: events_octa_raw_web_feed_reading

models:
  - name: trading_dynamics_rolling_aggregates
    description: "Model for viewing trading dynamics per user over time with rolling aggregates"
    columns:
      - name: user_id
        description: "Unique identifier for user"
        tests:
          - not_null
      - name: trading_account_id
        description: "Trading account identifier"
        tests:
          - not_null
      - name: symbol_name
        description: "Name of the traded symbol"
        tests:
          - not_null
      - name: period_start
        description: "Start of the period for the aggregate calculations (e.g., day, week, month)"
        tests:
          - not_null
      - name: cumulative_profit
        description: "Cumulative profit up to the end of the current period"
        tests:
          - not_null
      - name: cumulative_volume
        description: "Cumulative volume traded up to the end of the current period"
        tests:
          - not_null
      - name: avg_profit_per_period
        description: "Average profit per period up to the current period"
        tests:
          - not_null
      - name: avg_volume_per_period
        description: "Average volume per period up to the current period"
        tests:
          - not_null
      - name: cumulative_operations
        description: "Cumulative count of trading operations up to the end of the current period"
        tests:
          - not_null
      - name: period_profit
        description: "Profit earned during the current period"
        tests:
          - not_null
      - name: period_volume
        description: "Volume traded during the current period"
        tests:
          - not_null
      - name: profit_change_pct
        description: "Percentage change in profit from the previous period"
        tests:
          - not_null
      - name: volume_change_pct
        description: "Percentage change in volume from the previous period"
        tests:
          - not_null

  - name: trading_real_raw
    columns:
      - name: account_created_dt
        description: ""
        meta:
          dimension:
            type: timestamp
      - name: account_created_ut
        description: ""
        meta:
          dimension:
            type: number
      - name: balance
        description: ""
        meta:
          dimension:
            type: number
      - name: balance_at_close
        description: ""
        meta:
          dimension:
            type: number
      - name: balance_operation_type
        description: ""
        meta:
          dimension:
            type: number
      - name: close_price
        description: ""
        meta:
          dimension:
            type: number
      - name: close_time
        description: ""
        meta:
          dimension:
            type: number
      - name: close_time_dt
        description: ""
        meta:
          dimension:
            type: timestamp
      - name: close_time_since_acc_open
        description: ""
        meta:
          dimension:
            type: number
      - name: close_time_since_reg
        description: ""
        meta:
          dimension:
            type: number
      - name: cmd
        description: ""
        meta:
          dimension:
            type: number
      - name: comment
        description: ""
        meta:
          dimension:
            type: string
      - name: commission
        description: ""
        meta:
          dimension:
            type: number
      - name: conv_rate1
        description: ""
        meta:
          dimension:
            type: number
      - name: copy_trade_commission
        description: ""
        meta:
          dimension:
            type: number
      - name: equity_at_close
        description: ""
        meta:
          dimension:
            type: number
      - name: equity_at_open
        description: ""
        meta:
          dimension:
            type: number
      - name: expiration
        description: ""
        meta:
          dimension:
            type: number
      - name: is_closed_by_hedge
        description: ""
        meta:
          dimension:
            type: number
      - name: is_pending
        description: ""
        meta:
          dimension:
            type: number
      - name: leverage_at_open
        description: ""
        meta:
          dimension:
            type: number
      - name: login
        description: ""
        meta:
          dimension:
            type: number
      - name: margin_at_open
        description: ""
        meta:
          dimension:
            type: number
      - name: margin_rate
        description: ""
        meta:
          dimension:
            type: number
      - name: modify_time
        description: ""
        meta:
          dimension:
            type: number
      - name: open_price
        description: ""
        meta:
          dimension:
            type: number
      - name: open_time
        description: ""
        meta:
          dimension:
            type: number
      - name: open_time_dt
        description: ""
        meta:
          dimension:
            type: timestamp
      - name: operation_id
        description: ""
        meta:
          dimension:
            type: number
      - name: pending_created
        description: ""
        meta:
          dimension:
            type: number
      - name: pending_type
        description: ""
        meta:
          dimension:
            type: number
      - name: profit
        description: ""
        meta:
          dimension:
            type: number
      - name: reason
        description: ""
        meta:
          dimension:
            type: string
      - name: registered_dt
        description: ""
        meta:
          dimension:
            type: timestamp
      - name: registered_ut
        description: ""
        meta:
          dimension:
            type: number
      - name: shard
        description: ""
        meta:
          dimension:
            type: number
      - name: spread_close
        description: ""
        meta:
          dimension:
            type: number
      - name: spread_open
        description: ""
        meta:
          dimension:
            type: number
      - name: status
        description: ""
        meta:
          dimension:
            type: number
      - name: swap_free_commission
        description: ""
        meta:
          dimension:
            type: number
      - name: swaps
        description: ""
        meta:
          dimension:
            type: number
      - name: symbol_digits
        description: ""
        meta:
          dimension:
            type: number
      - name: symbol_name
        description: ""
        meta:
          dimension:
            type: string
      - name: trading_account_currency
        description: ""
        meta:
          dimension:
            type: string
      - name: trading_account_id
        description: ""
        meta:
          dimension:
            type: number
      - name: trading_account_leverage
        description: ""
        meta:
          dimension:
            type: number
      - name: type
        description: ""
        meta:
          dimension:
            type: number
      - name: user_id
        description: ""
        meta:
          dimension:
            type: number
      - name: volume
        description: ""
        meta:
          dimension:
            type: number
      - name: initial_open_operation_id
        description: ""
        meta:
          dimension:
            type: number
      - name: initial_open_volume
        description: ""
        meta:
          dimension:
            type: number
      - name: open_reason
        description: ""
        meta:
          dimension:
            type: string
      - name: position_id
        description: ""
        meta:
          dimension:
            type: number
      - name: platform_name
        description: ""
        meta:
          dimension:
            type: string
      - name: open_deal_price
        description: ""
        meta:
          dimension:
            type: number
